/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#006c49",
        "on-primary": "#ffffff",
        "primary-container": "#10b981",
        "on-primary-container": "#00422b",
        "inverse-primary": "#4edea3",
        "primary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#002113",
        "on-primary-fixed-variant": "#005236",
        secondary: "#b61722",
        "on-secondary": "#ffffff",
        "secondary-container": "#da3437",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#ffdad7",
        "secondary-fixed-dim": "#ffb3ad",
        "on-secondary-fixed": "#410004",
        "on-secondary-fixed-variant": "#930013",
        tertiary: "#005ac2",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#71a1ff",
        "on-tertiary-container": "#00367a",
        "tertiary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#adc6ff",
        "on-tertiary-fixed": "#001a42",
        "on-tertiary-fixed-variant": "#004395",
        surface: "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "surface-variant": "#dae2fd",
        "surface-tint": "#006c49",
        "on-surface": "#131b2e",
        "on-surface-variant": "#3c4a42",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        outline: "#6c7a71",
        "outline-variant": "#bbcabf",
        background: "#faf8ff",
        "on-background": "#131b2e",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "success-emerald": "#10b981",
      },
      spacing: {
        "space-xs": "4px",
        "space-sm": "8px",
        "space-md": "16px",
        "space-lg": "24px",
        "space-xl": "40px",
        "space-2xl": "64px",
        gutter: "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      fontSize: {
        display: [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px" }],
        "body-md": ["16px", { lineHeight: "24px" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", fontWeight: "500", letterSpacing: "0.01em" },
        ],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
